// <auto-generated />
using System;
using ERP_Ordini.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP_Ordini.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512220334_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ERP_Ordini.Models.DettagliOrdine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataOrdine")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdOrdine")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DettagliOrdine");
                });

            modelBuilder.Entity("ERP_Ordini.Models.Ordine", b =>
                {
                    b.Property<int>("IdOrdine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdOrdine"));

                    b.Property<int>("IdDettagliOrdine")
                        .HasColumnType("int");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.HasKey("IdOrdine");

                    b.HasIndex("IdDettagliOrdine")
                        .IsUnique();

                    b.ToTable("Ordini");
                });

            modelBuilder.Entity("ERP_Ordini.Models.Ordine", b =>
                {
                    b.HasOne("ERP_Ordini.Models.DettagliOrdine", "DettagliOrdine")
                        .WithOne("Ordine")
                        .HasForeignKey("ERP_Ordini.Models.Ordine", "IdDettagliOrdine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DettagliOrdine");
                });

            modelBuilder.Entity("ERP_Ordini.Models.DettagliOrdine", b =>
                {
                    b.Navigation("Ordine")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
