// <auto-generated />
using System;
using erp_corriere.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace erp_corriere.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("erp_corriere.Models.Spedizione", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int?>("AliquotaIva").HasColumnType("int");
                b.Property<string?>("Cap").HasColumnType("nvarchar(max)");
                b.Property<string>("Citta").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Corriere").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<decimal?>("CostoNetto").HasColumnType("decimal(10,2)");
                b.Property<DateTime?>("DataArrivoPrevista").HasColumnType("datetime2");
                b.Property<DateTime>("DataSpedizione").HasColumnType("datetime2");
                b.Property<string>("Destinatario").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string?>("Dimensioni").HasColumnType("nvarchar(max)");
                b.Property<string>("Indirizzo").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string?>("Note").HasColumnType("nvarchar(max)");
                b.Property<string>("Numero").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<decimal?>("PesoKg").HasColumnType("decimal(8,2)");
                b.Property<string>("Stato").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.ToTable("Spedizioni");
            });
#pragma warning restore 612, 618
        }
    }
}
